### PR TITLE
Update gage.shield.js

### PR DESCRIPTION
**Pull request by jda0**
Reset shield maximum if greater than DP.

### CODE REVIEW

**Comment by jda0** [comment]
Second thought: this affects the outcome when fighting the donsol, as it can be advantageous currently to fight the donsol in order to get very high durability on a weak shield to reduce HP taken by other enemies. It is not clear whether it is intented behaviour in this event is the current behaviour (20/X DP => 6/X after a fight against an Ogre (7); or X (new behaviour).

**Comment by jda0** [comment]
Edit: this does not enforce fighting enemies in descending order.

**Comment by neauoire** [comment]
Yeah, I was about to say.
It breaks the gameplay at the moment, makes the game much too easy.
I will revert, sorry :)

**Comment by jda0** [comment]
No, needed to steady my hand a little more. Absolutely on me.

**Comment by neauoire** [comment]
It's alright, for moment I was like, "wait yes"!
Don't hesitate if you find something weird anyways, let me know 👍

**Comment by jda0** [comment]
If I catch any weirdness I'll put in a new PR.
This is still a bug on reset so I've just put a quick fix there: #11 
Thanks, love & inspired by your stuff (and lifestyle tbh) :)

**Pull request merged**
