### PR TITLE
Simplify completion condition

### PR DESCRIPTION
**Pull request by jda0**
Finished a dungeon without it registering, change appears to fix & simplify.

### CODE REVIEW

**Comment by neauoire** [comment]
Let me do a few runs and try it out :)

**Comment by jda0** [comment]
Of course, almost a shame there's not a hidden walkthrough like Oquonie 😉

**Comment by Rezmason** [comment]
Confession: haven't played Donsol yet. I've meant to, but haven't yet. But I'll put it on the list of repos to poke around in, @neauoire ;)

**Comment by neauoire** [comment]
That PR works perfectly.

**Pull request merged**
